POST http://localhost:3003/api/products/
Content-Type: application/json

{
  "product": "Takka",
  "quantity": 1,
  "priceExclTax": 20,
  "priceInclTax": 24.5,
  "taxRate": 24,
  "discount": 0,
  "description": "Takan nuohous"
}